### ISSUE TITLE
PUT /person/:id - 405 Method Not Allowed error

### ISSUE THREAD

**Issue by ikbensiep** [badgateway/tt-api#20]
When updating a person's display name, the api will log `405 Method Not Allowed`. 

`=> (10) PUT /person/3`

```js
{
  type: null,
  httpStatus: 405,
  title: 'Method Not Allowed',
  detail: 'PUT is not allowed',
  instance: null,
  allow: [ 'GET', 'OPTIONS', 'POST' ]
}
```

**Comment by syedfkabir** [comment]
Hey @evert, as I was testing this, and looking through the API,
it seems the `Person` controller doesn't have a `PUT` method. 
It has a POST performing like a PUT. Not sure if this was intentional, I can change it to a `PUT`. 


Meaning a super quick fix @ikbensiep is just changing that code ^ from `PUT` to `POST` should work
