### ISSUE TITLE
Can't submit timesheet entries.

### ISSUE THREAD

**Issue by BeckyPollard** [badgateway/tt-api#36]
### Task Summary
Need to be able to submit/save timesheet entries to the API, either automatically or by hitting the SUBMIT button on the timesheet row.

![Screen Shot 2022-09-30 at 3 25 06 PM](https://user-images.githubusercontent.com/52248161/193342439-f279afc8-9696-45c3-914e-1e49b0091b23.png)

### Context

After some testing we found that the endpoint is making a POST request on `/person/1/sheet/2022/42`
Contextually, this doesn't make sense bc `person/1/entry` would be ideal next to this submit. 

After discussing with @evert and the gang, we came to the conclusion it would be best for
the endpoint: `/person/1/sheet/{year}/{week}`
to dynamically accept either a single day's entry or the entire weeks' entry.

**Comment by evert** [comment]
For context the frontend used `/person/1/entry` for getting the list of entries and submitting new entries. I added a new API route for reading per-week entries (`/person/1/sheet/{year}/{week}`) but this broke submissions because there was no POST request on that endpoint.

2 options for fixing this:

1. Accept POST requests on `/person/1/sheet/{year}/{week}`
2. Change the frontend to `POST` to `/person/1/entry`

I think both solutions are good, as long as in the end the backend supports only 1 way to do this, not both.

**Comment by syedfkabir** [comment]
> as long as in the end the backend supports only 1 way to do this, not both.

After some thought, I think the best approach is to change the frontend to POST to `/person/1/entry`
I understand how using `/person/1/sheet/{year}/{week}` can be done, but my argument would be 
we shouldn't overcomplicate this endpoint by giving it multiple jobs. Separation of concerns!

**Comment by syedfkabir** [comment]
https://github.com/badgateway/tt-app/issues/48 should resolve this issue
